indexWithoutLocale:
  path: /
  controller: App\Controller\Home::home

home:
  path: /{_locale}
  controller: App\Controller\Home::home
  requirements:
    _locale: en|bg

gps-new-version:
  path: /{_locale}/gps/new-version/{id}
  controller: App\Controller\Track::newVersion

gps-new:
  path: /{_locale}/gps/new
  controller: App\Controller\Track::new

gps-view:
  path: /{_locale}/gps/view/{id}
  controller: App\Controller\Track::view

gps-list:
  path: /{_locale}/gps/list/{neLat}/{neLon}/{swLat}/{swLon}/{size}
  defaults:
    size: 10
  controller: App\Controller\Home::find

gps-download:
  path: /{_locale}/gps/download/{id}
  controller: App\Controller\Track::download

app_logout:
  path: /logout
