index:
  path: /
  controller: App\Controller\Home::home

gps-new-version:
  path: /gps/new-version/{id}
  controller: App\Controller\Track::newVersion

gps-new:
  path: /gps/new
  controller: App\Controller\Track::new

gps-view:
  path: /gps/view/{id}
  controller: App\Controller\Track::view

gps-list:
  path: /gps/list/{neLat}/{neLon}/{swLat}/{swLon}/{size}
  defaults:
    size: 10
  controller: App\Controller\Home::find

gps-download:
  path: /gps/download/{id}
  controller: App\Controller\Track::download

app_logout:
  path: /logout