index:
  path: /
  controller: App\Controller\Home::home

gps-new:
  path: /gps/new
  controller: App\Controller\Gps::new

gps-view:
  path: /gps/view/{id}
  controller: App\Controller\Gps::view

gps-download:
  path: /gps/download/{id}
  controller: App\Controller\Gps::download
